// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBqlpRwziZMcma2Lh-SOGKe8LdoEkaZI0',
    appId: '1:466939134282:web:050bea4319936974d601b3',
    messagingSenderId: '466939134282',
    projectId: 'healthcare-app-659ef',
    authDomain: 'healthcare-app-659ef.firebaseapp.com',
    storageBucket: 'healthcare-app-659ef.firebasestorage.app',
    measurementId: 'G-Y7JVN8RBT3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPZKXTJOJiN_u1I9UqsO_4R_uxG1X-4WM',
    appId: '1:466939134282:android:0738250f715b9ed1d601b3',
    messagingSenderId: '466939134282',
    projectId: 'healthcare-app-659ef',
    storageBucket: 'healthcare-app-659ef.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvVP3M2HcbRmtBymNYlk9-aBdbh_yHWrU',
    appId: '1:466939134282:ios:ceb28d0408aff3b1d601b3',
    messagingSenderId: '466939134282',
    projectId: 'healthcare-app-659ef',
    storageBucket: 'healthcare-app-659ef.firebasestorage.app',
    iosBundleId: 'com.saadc.nextGenAiHealthcare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvVP3M2HcbRmtBymNYlk9-aBdbh_yHWrU',
    appId: '1:466939134282:ios:ceb28d0408aff3b1d601b3',
    messagingSenderId: '466939134282',
    projectId: 'healthcare-app-659ef',
    storageBucket: 'healthcare-app-659ef.firebasestorage.app',
    iosBundleId: 'com.saadc.nextGenAiHealthcare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBqlpRwziZMcma2Lh-SOGKe8LdoEkaZI0',
    appId: '1:466939134282:web:8cd27d39fd4a209cd601b3',
    messagingSenderId: '466939134282',
    projectId: 'healthcare-app-659ef',
    authDomain: 'healthcare-app-659ef.firebaseapp.com',
    storageBucket: 'healthcare-app-659ef.firebasestorage.app',
    measurementId: 'G-G08RYS35BV',
  );
}
